#!/usr/bin/env python
#
# Config file for RulesetAnalysis
#

# Path to accesslist database (generated by preprocessing script)
ACCESSLIST_DATABASE_FILENAME = 'accesslists.db'
ACCESSLIST_DATABASE = './input/{0}'.format(ACCESSLIST_DATABASE_FILENAME)

# Path to database of portnames to numbers, and vice versa
NAME_NUMBER_MAPPING = 'name-number-mappings.db'

# Maximum number of connections to store and report per firewall rule,
# additional connections are discarded
MAX_NUMBER_OF_CONNECTIONS_PER_RULE = 1000

